site_name: Slow Pulsar Search

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: amber

nav:
  - Introduction: index.md
  - L1 Intensity Data Processor: 1-l1-intensity-data-processor.md
  - RFI Excision: 2-rfi-excision.md
  - Beamformer: 3-beamformer.md
  - Dedispersion: 4-bonsai-dedispersion.md
  - H-HAT: 5-hhat.md
  - H-Hat Quality Control: 6-hhat-quality-control.md
  - H-Hat trigger stacking: 7-hhat-trigger-stacking.md
  - Candidates Processor: 8-candidates-processor.md
  - Candidates Intensity Trigger: 9-candidates-intensity-trigger.md
  - Database: a-database.md
  - Infracture: b-infrastructure.md
  
markdown_extensions:
  - attr_list
