#!/bin/bash
# Find transit time and beam for a variety of sources
#
# Relies on being able to talk to frb-master at `frb-vsop:8001` to do the actual calculation

if [[ $1 == "-h" ]]; then
    echo "Usage: $0 [SOURCE] [DATE]"
    echo "Find transit time and beam for a variety of sources"
    echo
    echo "Possible sources: B0531+21 (Crab), J2111+2106, B1919+21, B1920+21, B1922+20, B2315+21, CYG_A (CYGA)"
    echo "Case does not matter and the declination can be left out since all sources are unique in RA (i.e., 'b1919' is OK)"
    echo
    echo "Default source: Crab; default date: today"
    echo
    echo "Note: the default date will be today even if it means the transit has already passed"
    exit
fi
SRC=$(echo "${1:-B0531+21}" | tr A-Z a-z)
DATE=$(date -u --date="${2:-today}" +%Y-%m-%d)
case $SRC in
    b0011+47 )
        SRC=B0011+47
        ra=3.57396
        dec=47.77594
    ;;
    cyga | cyg_a )
        SRC=CYG_A
        ra=299.87
        dec=40.74
    ;;
    crab | b0531 | b0531+21 )
        SRC=B0531+21
        ra=83.5
        dec=22
    ;;
    j0640+22 | empty )
        SRC=J0640+22
        ra=100.00
        dec=22.00
    ;;
    j1503 | j1503+2111 )
        SRC=J1503+2111
        ra=225.9775
        dec=21.18592
    ;;
    j2111 | j2111+2106 )
        SRC=J2111+2016
        ra=317.86
        dec=20.96
    ;;
    b1839-04 )
        SRC=B1839-04
        ra=280.61038
        dec=-4.000422
    ;;
    b1919 | b1919+21 | j1921+2153 )
        SRC=B1919+21
        ra=290.436729
        dec=21.883958
    ;;
    b1920 | b1920+21 )
        SRC=B1920+21
        ra=290.72305
        dec=21.17832
    ;;
    b1922 | b1922+20 )
        SRC=B1922+20
        ra=291.16667
        dec=20.6675
    ;;
    kathryn | J2110+49)
        SRC=J2110+49
        ra=317.5
        dec=49.8
    ;;
    b2315+21 )
        SRC=B2315+21
        ra=349.4910079
        dec=21.8300053
    ;;
    j2315+58 )
        SRC=J2315+58
        ra=348.75
        dec=58.0
    ;;
    b2323+63 )
        SRC=B2323+63
        ra=351.3054983
        dec=63.2812117
    ;;
    *)
        echo "Unknown source: $SRC"
        exit 1
esac

echo "$SRC, $DATE"
curl -H "content-format: application/json" -d "{
           \"ra\": $ra,
           \"dec\": $dec,
           \"date\": \"$DATE\",
           \"timezone\": \"UTC\"
         }" frb-vsop:8001/v1/code/calculate-transit | jq .
