#!/bin/bash
# Start an sps acquisition on all eight beams in rows 56-63.

if [[ $1 == "-h" ]]; then
    echo "Usage: $0 [NCHAN]"
    echo "Starts an sps acquisition at given channel depth on all eight beams in rows 124-131."
    echo
    echo "NCHAN is the target number of channels in spshuff, and must be a power of two in range 1024..16384"
    echo "Data will be written in '/data/chime/sps/raw/YYYY/mm/dd/BEAM'."
    echo
    echo "Default nchan: 1024"
    echo
    echo "To stop the acquisition, run $0 0"
    exit
fi

set -euo pipefail

NCHAN=${1:-1024}
case "$NCHAN" in
    0 | 1024 | 2048 | 4096 | 8192 | 16384) : # ok
        ;;
    * ) echo "Not a valid NCHAN value: $NCHAN"
        exit
        ;;
esac

for beam in {124..127}; do
    rpc_client.py \
           --spulsar-writer-params "$beam" "$NCHAN" 1024 5 \
           /mnt/sps-data/rpchufftest \
           tcp://10.9.202.15:5555
done

for beam in 1{124..127}; do
    rpc_client.py \
           --spulsar-writer-params "$beam" "$NCHAN" 1024 5 \
           /mnt/sps-data/rpchufftest \
           tcp://10.7.205.17:5555
done

for beam in 2{124..127}; do
    rpc_client.py \
           --spulsar-writer-params "$beam" "$NCHAN" 1024 5 \
           /mnt/sps-data/rpchufftest \
           tcp://10.9.208.19:5555
done

for beam in 3{124..127}; do
    rpc_client.py \
           --spulsar-writer-params "$beam" "$NCHAN" 1024 5 \
           /mnt/sps-data/rpchufftest \
           tcp://10.9.212.11:5555
done

for beam in {128..131}; do
    rpc_client.py \
           --spulsar-writer-params "$beam" "$NCHAN" 1024 5 \
           /mnt/sps-data/rpchufftest \
           tcp://10.8.202.16:5555
done

for beam in 1{128..131}; do
    rpc_client.py \
           --spulsar-writer-params "$beam" "$NCHAN" 1024 5 \
           /mnt/sps-data/rpchufftest \
           tcp://10.6.205.18:5555
done

for beam in 2{128..131}; do
    rpc_client.py \
           --spulsar-writer-params "$beam" "$NCHAN" 1024 5 \
           /mnt/sps-data/rpchufftest \
           tcp://10.6.209.10:5555
done

for beam in 3{128..131}; do
    rpc_client.py \
           --spulsar-writer-params "$beam" "$NCHAN" 1024 5 \
           /mnt/sps-data/rpchufftest \
           tcp://10.8.212.12:5555
done
