#!/bin/bash
# Stop streaming an intensity acquisition on all four beams in a row (56-59)

if [[ $1 == "-h" ]]; then
    echo "Usage: $0 [ROW]"
    echo "Stops a running intensity acquisition on all four beams of the given row."
    echo
    echo "ROW can be only in range 56-59 because the script hard-codes talk to L1 instances that process those beams"
    echo "(Data will be available on frb-archiver5 in a subdirectory of '/data/frb-archiver/chime/intensity/raw/acq_data'.)"
    echo
    echo "NOTE: you should make sure the row matches that given by the preceding 'start-intensity'!!"
    echo
    echo "Default row: 59 (Crab)"
    exit
fi

set -euo pipefail

ROW=${1:-59}
if (( ROW < 56 || ROW > 59 )); then
    echo "ROW must be between 56 and 59, inclusive: $ROW"
    exit 1
fi

rpc_client.py \
    --stop-stream " " \
    --stream-base nfs \
    tcp://10.6.201.17:5555

rpc_client.py \
    --stop-stream " " \
    --stream-base nfs \
    tcp://10.8.204.19:5555

rpc_client.py \
    --stop-stream " " \
    --stream-base nfs \
    tcp://10.8.208.11:5555

rpc_client.py \
    --stop-stream " " \
    --stream-base nfs \
    tcp://10.6.211.13:5555
