#!/usr/bin/env python

import attr
import numpy as np
from beamformer import PATH
from scipy.interpolate import LinearNDInterpolator

"""
Note:
    map_ymw16.npy was copied from CHIME/FRB frb-l2l3 Repo:
    https://github.com/CHIMEFRB/frb-l2l3/tree/master/config/data/dm_checker
    on date: May 28, 2020

    map_ne2025.npy was generated using the Fortran NE2025 binary from mwprop
    (Ocker & Cordes 2026, arXiv:2602.11838) integrated to 30 kpc, on the same
    RA/Dec grid as the original NE2001_map.npy. Generate with: generate_ne2025_map.py
"""

import os as _os

_ne2025_map_path = PATH + "/data/NE2025_map.npy"
_ne2025_map_available = _os.path.exists(_ne2025_map_path)


@attr.s
class DMMap:
    map_ymw16 = np.load(PATH + "/data/YMW16_map.npy").T
    interp_map_ymw16 = LinearNDInterpolator(map_ymw16[:2].T, map_ymw16[2].T)

    if _ne2025_map_available:
        map_ne2025 = np.load(_ne2025_map_path).T
        interp_map_ne2025 = LinearNDInterpolator(map_ne2025[:2].T, map_ne2025[2].T)
    else:
        map_ne2025 = None
        interp_map_ne2025 = None

    def get_dm_ymw16(self, latitude: float, longitude: float) -> np.ndarray:
        """
        Uses a map of DM values generate by the YMW16 software to obtain maximum
        Galactic component of DM, given a position of the source.

        Parameters
        ----------

        latitude : float
            Declination, in units of degrees.

        longitude : float
            Right ascension, in units of degrees.

        Returns
        -------

        dm_ymw16
            Galactic DM predicted by YMW16, in units of pc cm^-3.


        Notes
        -----
        The YMW16 map is stored in a numpy file (YMW16_map.npy) that contains a non-uniform
        grid of right ascension, declination, and the corresponding maximum DM. The YMW16 grid
        was first generated using the same set of coordinates used to compute the NE2001 map.
        """

        # interpolate map, and used interpolated result to find approximate DM at header coordinates.
        return self.interp_map_ymw16(longitude, latitude)

    def get_dm_ne2025(self, latitude: float, longitude: float) -> np.ndarray:
        """
        Uses a map of DM values generated by the NE2025 model (Ocker & Cordes 2026)
        to obtain maximum Galactic component of DM, given a position of the source.

        Returns None if NE2025_map.npy has not been generated yet.

        Parameters
        ----------

        latitude : float
            Declination, in units of degrees.

        longitude : float
            Right ascension, in units of degrees.

        Returns
        -------

        dm_ne2025
            Galactic DM predicted by NE2025, in units of pc cm^-3, or None if
            the map is unavailable.
        """
        if self.interp_map_ne2025 is None:
            return None
        return self.interp_map_ne2025(longitude, latitude)
