name: benchmark

on:
  workflow_call:
    inputs:
      branch_name:
        type: string

jobs:
  update-image:
   # Create an image of your branch with the branch name as tag, and save it locally on the testbed since it'll only run there
    uses: chime-sps/champss_software/.github/workflows/image.yml@main
    secrets: inherit
    with:
      image_tag: ${{ inputs.branch_name || 'none' }}
      runs_on: sps-compute2
      build_locally: true
  run-tests:
    needs: update-image
    runs-on: sps-compute2 # Image is only saved here
    steps:
      - run: | # || true is used to ignore the stopping error if the container doesn't exist
          docker rm -f champss-${{ inputs.branch_name }} || true
      - uses: addnab/docker-run-action@v3
        with:
            image: local/champss_software:${{ inputs.branch_name }}
            options: --rm --name champss-${{ inputs.branch_name }} -v /data/chime/sps/raw_backup:/data/chime/sps/raw_backup -v /data/chime/sps/benchmark/${{ inputs.branch_name }}:/champss_module/benchmark/ -v /dev/shm:/dev/shm --shm-size=100gb
            image: local/champss_software:${{ inputs.branch_name }}
            # The following is only needed if running inside a Docker container
            run: |
              export NODE_NAME='sps-compute2'
              export CONTAINER_NAME='champss-${{ inputs.branch_name }}'
              chmod +x /module/champss/pipeline_batch_db/pipeline-scripts/run-benchmark.sh
              ./champss/pipeline_batch_db/pipeline-scripts/run-benchmark.sh '--using-docker'
      - run: |
          docker image rmi local/champss_software:${{ inputs.branch_name }}
