name: benchmark

on:
  workflow_call:
    inputs:
      branch_name:
        type: string

jobs:
  update-image:
   # Create an image of your branch with the branch name as tag, and save it locally on the testbed since it'll only run there
    uses: chime-sps/champss_software/.github/workflows/image.yml@main
    secrets: inherit
    with:
      image_tag: ${{ inputs.branch_name || 'none' }}
      build_locally: true
      runs_on: testbed
  run-tests:
    needs: update-image
    runs-on: testbed # Image is only saved here
    steps:
      - run: |
          docker rm -f champss-${{ inputs.branch_name }} || true
      - uses: addnab/docker-run-action@v3
        with:
            image: chimefrb/champss_software:${{ inputs.branch_name }}
            options: --rm --name champss-${{ inputs.branch_name }} -v /data/chime/sps/raw:/data/chime/sps/raw -v /data/chime/sps/benchmark/${{ inputs.branch_name }}:/data/chime/sps/benchmark -v /dev/shm:/dev/shm --shm-size=100gb
            # The following is only needed if running inside a Docker container
            run: |
              export NODE_NAME='ss1'
              export CONTAINER_NAME='champss-${{ inputs.branch_name }}'
              chmod +x /module/champss/pipeline_batch_db/pipeline-scripts/run-benchmark.sh
              ./champss/pipeline_batch_db/pipeline-scripts/run-benchmark.sh '--using-docker'
      - run: |
          docker image rmi chimefrb/champss_software:${{ inputs.branch_name }}
          docker builder prune -f


