name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  precommit:
    # First check avoid double checks from bot's automated release PR
    if: ${{ github.actor != 'github-actions' && github.event_name == 'pull_request' }}
    uses: chime-sps/champss_software/.github/workflows/precommit.yml@main
    secrets: inherit
  benchmark:
    if: ${{ github.actor != 'github-actions' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
    uses: chime-sps/champss_software/.github/workflows/benchmark.yml@main
    secrets: inherit
    with:
      branch_name: ${{ github.head_ref || 'benchmark' }}
  test:
    # Last check makes sure we're not building a test image if pushing to main, as that will already trigger a build in continuous-deployment.yml
    if: ${{ github.actor != 'github-actions' && (contains(github.event.head_commit.message, '[test]') == true) && github.event_name == 'push' && github.ref_name != 'main' }}
    uses: chime-sps/champss_software/.github/workflows/image.yml@main # Usually '@main' but testing this branch's image.yml
    secrets: inherit
    with:
      runs_on: self-hosted
      image_tag: ${{ github.ref_name || 'test' }}
      build_locally: false
