name: Example GitHub Actions Workflow

on:
  # push:
  #  branches:
  #    - adapt-code-for-local-docker-image-registry
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_job_1:
        type: boolean
        default: false
      run_job_2:
        type: boolean
        default: false
  workflow_call:
    inputs:
      run_job_1:
        type: boolean
        default: false
      run_job_2:
        type: boolean
        default: false
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

jobs:
  job1:
    if: ${{ inputs.run_job_1 == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          ls -la
  job2:
    if: ${{ inputs.run_job_2 == true }}
    runs-on: sps-compute1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          python -m pip install .
          python champss/example.py
