name: Example GitHub Actions Workflow

on:
  # push:
  #  branches:
  #    - adapt-code-for-local-docker-image-registry
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      run_job_1:
        type: boolean
        default: false
      run_job_2:
        type: boolean
        default: false
  workflow_call:
    inputs:
      run_job_1:
        type: boolean
        default: false
      run_job_2:
        type: boolean
        default: false
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

# How to run a GitHub Actions Workflow Dispatch from your CLI with inputs:
# gh workflow run .github/workflows/example.yml --ref adapt-code-for-local-docker-image-registry --field run_job_1=true --field run_job_2=true

jobs:
  job1:
    if: ${{ inputs.run_job_1 == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          ls -la
  job2:
    if: ${{ inputs.run_job_2 == true }}
    needs: job1
    # Currently, only can spawn jobs from Docker Swarm manager nodes, e.g. sps-archiver[1-2]
    runs-on: sps-archiver1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: webfactory/ssh-agent@v0.4.1
        id: set-ssh
        with:
          ssh-private-key: ${{ secrets.SPS_SSH_ID }}
      - run: |
          ssh-keyscan github.com >> /root/.ssh/known_hosts
      - run: |
          python -m pip install .
          workflow workspace set champss.workspace.yml
          python champss/example.py
