name: Image

on:
 workflow_call:
    inputs:
      image_tag:
        type: string
      build_locally:
        type: boolean
      runs_on:
        type: string
        default: 'testbed'

jobs:
  build-image-and-push-to-remote:
    # NEEDS to run on self-hosted GitHub runners because spshuff requires AVX2
    # supported CPUs for the image to build. Use testbed, as steps will be too slow
    # when processing is running on site + testbed upload speed is much faster
    if: ${{ inputs.build_locally == false }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: webfactory/ssh-agent@v0.4.1
        id: set-ssh
        with:
          ssh-private-key: ${{ secrets.SPS_SSH_ID }}
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          target: runtime
          tags: |
            chimefrb/champss_software:${{ inputs.image_tag }}
          ssh: "github_ssh_id=${{ steps.set-ssh.outputs.SSH_AUTH_SOCK}}"
          push: true
  build-image-and-save-to-local:
    if: ${{ inputs.build_locally == true }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: webfactory/ssh-agent@v0.4.1
        id: set-ssh
        with:
          ssh-private-key: ${{ secrets.SPS_SSH_ID }}
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - run: |
          DOCKER_BUILDKIT=1 docker build -f Dockerfile -t chimefrb/champss_software:${{ inputs.image_tag }} --ssh github_ssh_id=${{ steps.set-ssh.outputs.SSH_AUTH_SOCK}} --load .